services:
  charlie:
    build:
      context: ../..
      dockerfile: .devcontainer/docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ../..:/workspace:cached
      - $HOME/.aws/:/home/user/.aws
      - $HOME/.ssh/:/home/user/.ssh
      - $HOME/.npmrc:/home/user/.npmrc
      - $HOME/.yalc:/home/user/.yalc
    command: sleep infinity
    networks:
      - default
networks:
  default: {}
